// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5DEPGLZeNV8M3Jiv2mMVhrmwaC_eDX8M',
    appId: '1:585481478030:web:75761de8e76c382e390edf',
    messagingSenderId: '585481478030',
    projectId: 'mynoting',
    authDomain: 'mynoting.firebaseapp.com',
    storageBucket: 'mynoting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu54ot47kIEdKl91sjJOvXvus3LF24CZY',
    appId: '1:585481478030:android:581e3a7c03f0a0ec390edf',
    messagingSenderId: '585481478030',
    projectId: 'mynoting',
    storageBucket: 'mynoting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXXqGmX1MpggihT0F3jT8DuFOUk5G_lU4',
    appId: '1:585481478030:ios:619343095923bd6c390edf',
    messagingSenderId: '585481478030',
    projectId: 'mynoting',
    storageBucket: 'mynoting.appspot.com',
    iosClientId: '585481478030-7sadd7k58sotu5egc44bhs28j46mhd82.apps.googleusercontent.com',
    iosBundleId: 'com.dena.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXXqGmX1MpggihT0F3jT8DuFOUk5G_lU4',
    appId: '1:585481478030:ios:619343095923bd6c390edf',
    messagingSenderId: '585481478030',
    projectId: 'mynoting',
    storageBucket: 'mynoting.appspot.com',
    iosClientId: '585481478030-7sadd7k58sotu5egc44bhs28j46mhd82.apps.googleusercontent.com',
    iosBundleId: 'com.dena.mynote',
  );
}
